print("On 9th feb I have birthday")
print("Mera Gsoc hoga esse saal")
print("Mai esse saal gsoc mai select hojunga")
print("Mera gsoc hoga")
print("Mera gosc pakka hoga")
print("Mera gsoc hoga esse saal")