print("On 9th feb I have birthday")
print("Mera Gsoc hoga esse saal")
print("Mai esse saal gsoc mai select hojunga")
print("Mera gsoc hoga")
print("Mera gosc pakka hoga")
print("Mera gsoc hoga esse saal")
print("Mera gsoc hoag eese saal maintainer mujhe hee select karega")
print("Mera gsoc hoag eese saal maintainer mujhe hee select karega")
print("Mera gsoc ess saal pakka hoga")
