print("On 9th feb I have birthday")
print("Mera Gsoc hoga esse saal")
print("Mai esse saal gsoc mai select hojunga")
print("Mera gsoc hoga")
print("Mera gosc pakka hoga")
print("Mera gsoc hoga esse saal")
print("Mera gsoc hoag eese saal maintainer mujhe hee select karega")
print("Mera gsoc hoag eese saal maintainer mujhe hee select karega")
print("Mera gsoc ess saal pakka hoga")
print("Mera gsoc pakka hoga vo bhi dono org's mai")
print("Mera gsoc pakka hoga or PR bhi jyda hogi")
print("Mera gsoc hoga")
print("Mera gsoc 100% hoga essse saal")
print("ABbb toh mera gsoc hona pakka ho gya")
print("Mera gsoc pakka hoga")
print("Maintainer mujhe hee select karega gsoc ke liye")
print("Mera selcetion pakka hoga hr haal mai")

